name: Build and Release Electron App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Set to your preferred Node.js version
    
    - name: Install dependencies
      run: |
        npm install
        npm run build
    
    - name: Build Electron App
      run: npm run package  # Ensure you have a package script defined in package.json

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: electron-app
        path: dist/  # The folder where your built Electron app will be stored

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install dependencies
      run: |
        npm install

    - name: Create GitHub Release
      uses: ghactions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: 'Release for version ${{ github.ref }}'
        draft: false
        prerelease: false

    - name: Upload assets to release
      uses: ghactions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/your-app-name
        asset_name: your-app-name.zip  # Name the asset correctly
        asset_content_type: application/zip  # Set the appropriate content type
